//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_inventario_
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Xunit;

    public partial class Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulo()
        {
            this.Existencias_Por_Almacen = new HashSet<Existencias_Por_Almacen>();
            this.Transacciones = new HashSet<Transacciones>();
        }
    
        public string Id_Articulo { get; set; }
        public string Descripcion { get; set; }
        public bool Existencia { get; set; }
        public string Id_Tipo_Inv { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "El costo debe ser mayor que cero")]
        public decimal Costo_Unitario { get; set; }
        public bool Estados { get; set; }
    
        public virtual Tipo_Inv Tipo_Inv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Existencias_Por_Almacen> Existencias_Por_Almacen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacciones> Transacciones { get; set; }
    }
}
